- name: install java
  apt: pkg=openjdk-7-jre-headless

- name: "get ES GPG key"
  shell: "wget -qO - https://packages.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -"

- name: "add elasticsearch package source"
  shell: 'echo "deb http://packages.elastic.co/elasticsearch/2.x/debian stable main" | sudo tee -a /etc/apt/sources.list.d/elasticsearch-2.x.list'

- name: "update apt"
  shell: "apt-get update"

- name: "install elasticsearch"
  apt: pkg=elasticsearch

- name: "update init script"
  command: "sudo update-rc.d elasticsearch defaults 95 10"
  notify:
    - restart elasticsearch

- name: "copy es config"
  copy: src={{elasticsearch_config_file}} dest=/etc/elasticsearch/elasticsearch.yml
  notify:
    - restart elasticsearch
