- name: "install nginx"
  apt: pkg=nginx

- name: update ngnix config
  copy: src={{nginx_config_file}} dest=/etc/nginx/nginx.conf
  notify:
    - restart nginx

- name: delete default app from sites-enabled
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify:
    - restart nginx

- name: delete default app from sites-available
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify:
    - restart nginx
